<<<<<<< HEAD
# Generated by Django 2.0.3 on 2018-07-10 03:45
=======
# Generated by Django 2.0.3 on 2018-07-08 23:53
>>>>>>> landing-Admin

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='Correo Electrónico')),
                ('rut', models.IntegerField(unique=True, verbose_name='RUT')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('puede_reservar', models.BooleanField(default=True, verbose_name='Habilitado para Reservar')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Es Administrador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Ingrese una breve descripcion del articulo', max_length=1000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID unica para este articulo', primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='templates/media/')),
                ('estado', models.CharField(blank=True, choices=[('d', 'Disponible'), ('o', 'Ocupado'), ('rp', 'En reparacion'), ('p', 'Perdido')], default='d', help_text='Estado del articulo', max_length=1)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo_articulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID unica para este prestamo', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(null=True)),
                ('hora_inicio', models.TimeField(null=True)),
                ('fecha_devolucion', models.DateField(null=True)),
                ('hora_devolucion', models.TimeField(null=True)),
                ('fecha_hora_peticion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(blank=True, choices=[('p', 'Pendiente'), ('a', 'Aceptado'), ('r', 'Rechazado'), ('c', 'Caducado'), ('t', 'Terminado')], default='p', help_text='Estado del prestamo', max_length=1)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario_CEI.Articulo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_hora_peticion'],
            },
        ),
    ]
