# Generated by Django 2.0.3 on 2018-07-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_CEI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.CharField(blank=True, choices=[('d', 'Disponible'), ('e', 'En Prestamo'), ('p', 'Perdido')], default='d', help_text='Estado del prestamo', max_length=1),
        ),
    ]
