# Generated by Django 2.0.3 on 2018-07-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_CEI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva_espacio',
            name='fecha_hora_peticion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva_espacio',
            name='hora_devolucion',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserva_espacio',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
    ]
