# Generated by Django 2.0.3 on 2018-07-09 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_CEI', '0002_articulo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID unica para este espacio', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, choices=[('d', 'Disponible'), ('e', 'En Prestamo')], default='d', help_text='Estado del prestamo', max_length=1)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva_espacio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID unica para esta reserva', primary_key=True, serialize=False)),
                ('fecha_devolucion', models.DateField(null=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('estado', models.CharField(blank=True, choices=[('p', 'Pendiente'), ('a', 'Aceptado'), ('r', 'Rechazado')], default='p', help_text='Estado del prestamo', max_length=1)),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario_CEI.Espacio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_devolucion'],
            },
        ),
    ]
